# You're in ChristmasFireworks config-file. Welcome and merry Christmas!
# Author: NoLogic

# -- CROSSBOW SETTINGS --
# You can localize the name of charged projectile here. 
# Also you can change the item that required for charge a crossbow.
# Use "§"-symbol for color choosing. Not the "&".
Crossbow:
    ChargedProjectileName: "§cChristmas Firework§r"
    Charger: REDSTONE

# -- FIREWORK SETTINGS --
# Here you can choose the color palette that used when custom fireworks detonate. Possible values is CHRISTMAS and RANDOM.
# CHRISTMAS is default christmas colors. (white, red, green, yellow, etc.)
# RANDOM is an absolutely random RGB color.
Firework:
    Detonate:
        ColorPalette: CHRISTMAS
        # How much additional colors you will see when firework explode?
        AdditionalColors: 2
    Fade:
        ColorPalette: RANDOM
        AdditionalColors: 2
    # If set true, fireworks will always have trails/flickers effects after detonate.
    # If false, trails and flickers will appear randomly.
    AlwaysTrailing: false
    AlwaysFlickering: false
    # Possible values: BALL, BALL_LARGE, BURST, CREEPER, STAR
    AllowedExplosionEffectTypes:
    - BALL
    - BALL_LARGE
    - BURST
    - CREEPER
    - STAR

# -- TASK SETTINGS --
# And last but not least, fireworks spawn task configuration.
# Duration represents the amount of ticks that task will active.
# Frequency is the period in ticks between each firework will spawn. Lower values will force fireworks to spawn faster, but it may reduce your TPS.
# ZERO FREQUENCY VALUE WILL ENDLESSLY LOOP THE TASK AND PROBABLY DESTROY YOUR SERVER.
Task:
    Duration: 400
    Frequency: 4
    
# P. S. Somewhere my English may be bad. Sorry for that, it's not my main language. =)